from os import getenv
from dotenv import load_dotenv

load_dotenv()

GOOGLE_GEMINI_MODEL_NAME = getenv("GOOGLE_GEMINI_MODEL_NAME")
GOOGLE_GEMINI_API_KEY = getenv("GOOGLE_GEMINI_API_KEY")
GOOGLE_GEMINI_TEMPERATURE = getenv("GOOGLE_GEMINI_TEMPERATURE")

OPENROUTER_API_KEY = getenv("OPENROUTER_API_KEY")
OPENROUTER_BASE_URL = getenv("OPENROUTER_BASE_URL")
OPENROUTER_MODEL_NAME = getenv("OPENROUTER_MODEL_NAME")

JINA_API_KEY = getenv("JINA_API_KEY")